# Generated by Django 5.2.16 on 2026-07-11 14:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(blank=True, default='', max_length=120, verbose_name='Société')),
                ('subject', models.CharField(blank=True, default='', max_length=160, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('handled', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, default='', verbose_name='Lien')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Logo partenaire',
                'verbose_name_plural': 'Logos partenaires',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=120, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('summary_fr', models.TextField(verbose_name='Résumé (FR)')),
                ('summary_en', models.TextField(verbose_name='Summary (EN)')),
                ('icon', models.CharField(default='rail', help_text='rail, cargo, network, shield, bolt, globe', max_length=40, verbose_name='Icône (nom)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('featured', models.BooleanField(default=True, verbose_name='Mis en avant')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'id'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_fr', models.CharField(max_length=80, verbose_name='Libellé (FR)')),
                ('label_en', models.CharField(max_length=80, verbose_name='Label (EN)')),
                ('value', models.PositiveIntegerField(verbose_name='Valeur')),
                ('suffix', models.CharField(blank=True, default='', max_length=8, verbose_name='Suffixe')),
                ('prefix', models.CharField(blank=True, default='', max_length=8, verbose_name='Préfixe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['order', 'id'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=12, verbose_name='Année')),
                ('title_fr', models.CharField(max_length=120, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('body_fr', models.TextField(verbose_name='Description (FR)')),
                ('body_en', models.TextField(verbose_name='Description (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Étape (timeline)',
                'verbose_name_plural': 'Timeline',
                'ordering': ['order', 'id'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
    ]
