# Generated by Django 5.2.16 on 2026-07-11 16:59

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=160, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=160, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('excerpt_fr', models.TextField(verbose_name='Chapô (FR)')),
                ('excerpt_en', models.TextField(verbose_name='Excerpt (EN)')),
                ('body_fr', models.TextField(verbose_name='Contenu (FR)')),
                ('body_en', models.TextField(verbose_name='Content (EN)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image de couverture')),
                ('category_fr', models.CharField(blank=True, default='Actualité', max_length=60, verbose_name='Catégorie (FR)')),
                ('category_en', models.CharField(blank=True, default='News', max_length=60, verbose_name='Category (EN)')),
                ('published_at', models.DateTimeField(verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fr', models.CharField(max_length=200, verbose_name='Question (FR)')),
                ('question_en', models.CharField(max_length=200, verbose_name='Question (EN)')),
                ('answer_fr', models.TextField(verbose_name='Réponse (FR)')),
                ('answer_en', models.TextField(verbose_name='Answer (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=160, verbose_name='Poste (FR)')),
                ('title_en', models.CharField(max_length=160, verbose_name='Position (EN)')),
                ('location', models.CharField(default='Lomé, Togo', max_length=120, verbose_name='Lieu')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('alternance', 'Alternance')], default='cdi', max_length=20, verbose_name='Contrat')),
                ('description_fr', models.TextField(verbose_name='Description (FR)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['order', 'id'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=160, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=160, verbose_name='Title (EN)')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('summary_fr', models.TextField(verbose_name='Résumé (FR)')),
                ('summary_en', models.TextField(verbose_name='Summary (EN)')),
                ('body_fr', models.TextField(blank=True, default='', verbose_name='Étude de cas (FR)')),
                ('body_en', models.TextField(blank=True, default='', verbose_name='Case study (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image')),
                ('year', models.CharField(blank=True, default='', max_length=12, verbose_name='Année')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Lieu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-year'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Auteur')),
                ('role_fr', models.CharField(max_length=120, verbose_name='Fonction (FR)')),
                ('role_en', models.CharField(max_length=120, verbose_name='Role (EN)')),
                ('quote_fr', models.TextField(verbose_name='Citation (FR)')),
                ('quote_en', models.TextField(verbose_name='Quote (EN)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order', 'id'],
            },
            bases=(core.models.LocalizedMixin, models.Model),
        ),
        migrations.AddField(
            model_name='service',
            name='body_en',
            field=models.TextField(blank=True, default='', verbose_name='Detailed description (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='body_fr',
            field=models.TextField(blank=True, default='', verbose_name='Description détaillée (FR)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Téléphone')),
                ('cv', models.FileField(upload_to='cv/', verbose_name='CV')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.joboffer', verbose_name='Offre')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
